# Generated by Django 3.2.7 on 2021-10-05 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariokart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.CharField(choices=[('L', 'Lightweight'), ('M', 'Middleweight'), ('H', 'Heavyweight')], max_length=1, unique=True),
        ),
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('speed', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('acceleration', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('handling', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('drift', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariokart.weight')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('flavor_text', models.CharField(default='They drive fast!', max_length=100)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mariokart.weight')),
            ],
        ),
    ]
